### PR TITLE
Fix error in generated  javascript from coffee

### PR DESCRIPTION
**Pull request by julien-duponchelle**
I don't know why it stop working for us but this lines start to stop working for us. When we have debug the generated javascript we found something strange.

The current code generate this:

```
new App.Models.ReadingPosition)({
```

But we think it should be:

```
new App.Models.ReadingPosition({
```

You can try the two syntax here:
http://coffeescript.org/#try:%23Invalid%20JS%0A%20%20%20%20%40model.set%20'readingPosition'%2C%20new%20App.Models.ReadingPosition%0A%20%20%20%20%20%20book_id%3A%20%40model.id%0A%20%20%20%20%20%20user_id%3A%20App.current_user.id%0A%0A%0A%23Valid%20JS%0A%0A%20%20%20%20%40model.set('readingPosition'%2C%20new%20App.Models.ReadingPosition(book_id%3A%20%40model.id%2C%20user_id%3A%20App.current_user.id))%0A%0A

### CODE REVIEW

**Comment by eunomie** [comment]
> I don't know why it stop working for us

Do you use coffee 1.5.0?

Sounds like a coffeescript bug, because it works fine with coffee 1.4.0.

If I compile your example with coffee 1.4.0 :

``` javascript
this.model.set('readingPosition', new App.Models.ReadingPosition({
  book_id: this.model.id,
  user_id: App.current_user.id
}));

this.model.set('readingPosition', new App.Models.ReadingPosition({
  book_id: this.model.id,
  user_id: App.current_user.id
}));
```

With the latest 1.5.0 :

``` javascript
this.model.set('readingPosition', new App.Models.ReadingPosition)({
  book_id: this.model.id,
  user_id: App.current_user.id
});

this.model.set('readingPosition', new App.Models.ReadingPosition({
  book_id: this.model.id,
  user_id: App.current_user.id
}));
```

**Comment by julien-duponchelle** [comment]
I check our gemfile and we have coffee 1.5.0 nice catch

**Comment by julien-duponchelle** [comment]
It seem fixed in coffee 1.6.1

**Comment by edas** [comment]
Thank you both of you

**Pull request closed without merging**
