### PR TITLE
Getting started instructions

### PR DESCRIPTION
**Pull request by j15e**
Hi! 

Just gave a try, so I added instruction to setup the project.

I haven't found how you expect to create/manage users, you should add this to the getting started instructions I made if possible

Thank you

### CODE REVIEW

**Comment by eunomie** [comment]
Hi,

Thanks for your comment.
As you have seen the documentation is not yet complete.
This will happen gradually.

User accounts are not in the application. They are in another server and the communication is done via an [API](https://github.com/TEA-ebook/teabook-open-reader/wiki/Api).
To test the application, a fake API is available. You can launch it by running the command

```
bundle exec shotgun tea_api.ru-p 4567
```

With the fake API, authentication always responds ok.

Even if it does not answer the question exactly, you can find some additional instructions in the commit e9e528e870 to create a vagrant virtual machine to test the application.

**Comment by j15e** [comment]
Thx for the details

Can you merge my instructions as a starting point?

**Comment by nono** [comment]
At least, there should be a link to https://github.com/TEA-ebook/teabook-open-reader/wiki/Installation in the README. It's not obvious to find it when you have git cloned the repos and are trying to use it.

**Comment by eunomie** [comment]
You can find a more detailed readme here https://github.com/CrEv/teabook-open-reader/tree/readme

**Comment by eunomie** [comment]
I've commited a more detailed readme (0c602b13c6)

I added some commands from your commit (rails g/s commands) in addition to those used in general

Thanks

**Pull request closed without merging**
