### PR TITLE
Broken demo: Mod: update sticky.js to 2.9

### PR DESCRIPTION
**Pull request by eunomie**
The demo (http://demo-open-reader.tea-ebook.com/) is broken with chrome 25+.

This is just a little patch to upgrade version of sticky.js to 2.9. See https://github.com/TEA-ebook/teabook-open-reader/issues/29 for some details.

I have not tested but the difference between 2.8 and 2.9 is mainly the patch by @noplay and the other part is just an other way to access indexedDB outside global namespace.

### CODE REVIEW

**Comment by julien-duponchelle** [comment]
Anynews about that?

**Comment by imjufu** [comment]
Hi guys, sorry for the late reply. Thanks for this PR @CrEv!
After testing your PR, i see that you forgot 2 files and the reader is broken. Oopsie.
https://github.com/TEA-ebook/teabook-open-reader/blob/master/app/assets/javascripts/reader/lib.js#L32
https://github.com/TEA-ebook/teabook-open-reader/blob/master/app/assets/javascripts/reader_sandbox/lib.js#L36
Could you fix it ? I merge your PR asap!

**Comment by eunomie** [comment]
@Koin: :ballot_box_with_check:

**Comment by imjufu** [comment]
:+1:

**Pull request merged**
